# Generated by Django 5.2.3 on 2025-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'db_table': 'city_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'db_table': 'district_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('create', models.DateTimeField(blank=True, db_column='create_', null=True)),
                ('delete', models.DateTimeField(blank=True, db_column='delete_', null=True)),
                ('address', models.CharField(blank=True, db_column='address_', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, db_column='telephone_', max_length=255, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax_', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='email_', max_length=255, null=True)),
                ('type_firm', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.CharField(blank=True, db_column='tax_', max_length=255, null=True)),
                ('web', models.CharField(blank=True, db_column='web_', max_length=255, null=True)),
                ('sgk_sicil', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, db_column='payment_', max_length=255, null=True)),
                ('ceo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_email', models.CharField(blank=True, max_length=255, null=True)),
                ('ceo_cell', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(db_column='active_')),
            ],
            options={
                'db_table': 'firm_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('short', models.CharField(blank=True, db_column='short_', max_length=255, null=True)),
            ],
            options={
                'db_table': 'language_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(blank=True, db_column='create_', null=True)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('delete', models.DateTimeField(blank=True, db_column='delete_', null=True)),
                ('active', models.BooleanField(db_column='active_')),
            ],
            options={
                'db_table': 'media_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
            ],
            options={
                'db_table': 'media_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('code', models.CharField(db_column='code_', max_length=15)),
                ('description', models.CharField(db_column='description_', max_length=511)),
            ],
            options={
                'db_table': 'nace_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'db_table': 'path_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxOffice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'db_table': 'tax_office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('tckno', models.CharField(blank=True, db_column='tckno_', max_length=11, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='title_', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='email_', max_length=255, null=True)),
                ('active', models.BooleanField(db_column='active_')),
            ],
            options={
                'db_table': 'user_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFirm',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'firm_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(db_column='create_')),
            ],
            options={
                'db_table': 'user_firm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='description_', max_length=511, null=True)),
            ],
            options={
                'db_table': 'user_group',
                'managed': False,
            },
        ),
    ]
